[package]
name = "ucsc-ectf-eeprom-layout"
version = "0.1.0"
edition = "2021"
authors = ["2023 UCSC eCTF Team"]
categories = ["embedded", "no-std"]
license = "MIT"

[profile.release]
lto = true
codegen-units = 1
debug = false
strip = true
