[package]
name = "ucsc-ectf-enable-feature"
version = "0.1.0"
edition = "2021"
authors = ["2023 UCSC eCTF Team"]
license = "MIT"

[dependencies]
ucsc-ectf-util-std = { path = "../../docker_env/util_std" }
